name: 'debug'
on:
  workflow_dispatch # only run manually
  # pull_request:
  # push:
  #   branches:
  #     - main
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo meow
