# https://github.com/slidevjs/slidev/issues/1171#issue-1971433289
name: Build slides and deploy to gh-pages

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'example/**'
      - '.devcontainer/**'
      - '!slides/**'
  workflow_dispatch: # trigger workflows manually on gh

jobs:
  build:
    env:
      DEBUG: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # - name: install yarn1
      #   run: npm install -g yarn
      # https://github.com/actions/setup-node/issues/182#issuecomment-966885975
      # - name: Install node again with caching enabled
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     #cache: yarn
      - name: Install dependencies
        run: |
          cd slides
          npm i
      - name: Install global dependencies
        run: |
          cd slides
          npm i -g @slidev/cli
          npm i -g @slidev/theme-seriph
      - name: Create empty dist folder in slides folder
        run: |
          cd slides
          mkdir ../dist
      - name: DEBUG
        if: env.DEBUG != 'false'
        run: |
          cd slides
          ls
      - name: Build slides in dist folder with basepath
        run: |
          cd slides
          slidev build --base /monte/
      - name: DEBUG
        if: env.DEBUG != 'false'
        run: |
          ls
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          folder: slides/dist
          jekyll: false
          token: ${{ secrets.GITHUB_TOKEN }}
