defaults:
  run:
    working-directory: slides

name: Build slides and deploy to gh-pages branch

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'example/**'
      - '.devcontainer/**'
      - '!slides/**'
  workflow_dispatch: # trigger workflows manually on gh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run: npm i -g @slidev/cli
      - name: Create dist folder
        run: |
          mkdir ../dist
      - name: Build
        run: slidev build --base /monte
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: slides/dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
